<a href="https://colab.research.google.com/github/GundaTejeshwari/MACHINE_LEARNING/blob/main/MACHINE_LEARNING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

LINEAR ALGEBRA

** Scalar/Vector/Matrix/Tensor**

In [3]:
#SCALAR
import numpy as np
scalar = np.array(5)
print(type(scalar))
print(scalar.ndim)
print(scalar.shape)


<class 'numpy.ndarray'>
0
()


In [10]:
scalar

array(5)

In [8]:
#VECTOR
vector = np.array([1,2,3,4,5])
print(type(vector))
print(vector.ndim)
print(vector.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
(5,)


In [9]:
vector

array([1, 2, 3, 4, 5])

In [16]:
#MATRIX
matrix = np.array([[1,2,3,],[4,5,6]])
print(type(matrix))
print(matrix.ndim)
print(matrix.shape)

<class 'numpy.ndarray'>
2
(2, 3)


In [17]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
#TENSOR
tensor = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print(type(tensor))
print(tensor.ndim)
print(tensor.shape)

<class 'numpy.ndarray'>
3
(2, 2, 3)


In [23]:
tensor

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

OPERATIONS ON MATRIX


In [28]:
#Matrix addition and subtraction
matrix1 = np.array([[1,2,3],
                    [4,5,6]])
matrix2 = np.array([[1,2,3],
                    [4,5,6]])
print(matrix1+matrix2)
print(matrix1-matrix2)

[[ 2  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]


In [26]:
matrix1


array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
matrix2

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
#SCALAR MULTIPLICATION
a = np.array([[1,2],
             [3,4]])
sclar = 10
print(scalar*a)

[[ 5 10]
 [15 20]]


In [32]:
#DOT PRODUCT OF VECTORS
# @ and dot() is used to calculate the dot product
vec1 = np.array([3,4])
vec2 = np.array([1,2])
print(vec1 @ vec2)
print(np.dot(vec1,vec2))

11
11


In [33]:
#DOT PRODUCT ON MULTIPLICATION
mat1 = np.array([[1,2],
             [3,4]])
mat2 = np.array([[1,2],
             [3,4]])
print(np.dot(mat1,mat2))


[[ 7 10]
 [15 22]]


In [34]:
#TRANSPOSE OF A MATRIX
mat1 = np.array([[1,2],
             [3,4]])
print(mat1.T)

[[1 3]
 [2 4]]


In [35]:
#DETERMINANT OF MATRIX
mat1 = np.array([[1,2],
             [3,4]])
print(np.linalg.det(mat1))

-2.0000000000000004


In [37]:
#EIGEN VALUE AND EIGEN VECTOR
eig_val,eig_vec =np.linalg.eig(mat1)
print(eig_val)

print(eig_vec)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [38]:
#INVERSE OF A MATRIX
mat1 = np.array([[1,2],
             [3,4]])
print(np.linalg.inv(mat1))

[[-2.   1. ]
 [ 1.5 -0.5]]
